### PR TITLE
Switch to Webpack instead of Browserify

### PR DESCRIPTION
**Pull request by kring**
And also clean up the build process quite a bit.  Some of the improvements here:
- Added support for ES2015 via Babel.
- Incremental builds now take less than 1 second on my system, instead of 5-6 seconds.
- There's now a clearer separation between gulp tasks run when TerriaJS is `npm install`ed and those that are run in the course of development.  This should fix problems like the recent one where an explicit `npm install karma` was necessary when using TerriaJS from git instead of npm.
- It puts us in a good position to do a bunch of other cool things, like described in #1419.
- Adds a handy landing page on `http://localhost:3001/` with links to the tests, doc, etc.
- Removes the custom `server.js` and instead uses `terriajs-server` to host the web server used to run the tests.

### CODE REVIEW

**Comment by kring** [comment]
(NationalMap branch to use with this coming soon!)

File: .eslintrc [hunk 1]
```diff
@@ -0,0 +1,199 @@
...
+        "constructor-super": 1,
+        "generator-star-spacing": 0, // see Babel section
+        "no-this-before-super": 1,
+        "no-var": 0,
+        "object-shorthand": 0, // see Babel section
+        "prefer-const": 1
+
+    },
+    "plugins": [
+        //"react"
```
Comment (AlexGilleran) [inline .eslintrc:197]: so this isn't needed because of babel-eslint?

EDIT: oh right this is master so no react, I get it

File: buildprocess/configureWebpack.js [hunk 2]
```diff
@@ -0,0 +1,59 @@
+'use strict';
+
+/*global require*/
```
Comment (AlexGilleran) [inline buildprocess/configureWebpack.js]: Does this file get linted? If so doesn't the commonJS thing in eslintrc fix it?

Comment (kring) [inline buildprocess/configureWebpack.js]: It doesn't get linted by `gulp lint` but your editor will probably lint it (mine does).  I'm not sure exactly what you're asking though.  Are you asking if the `global require` is needed?

Comment (AlexGilleran) [inline buildprocess/configureWebpack.js]: Yeah - all of these `/\* global require */ things should be superfluous after you've told .eslintrc to allow it

Comment (kring) [inline buildprocess/configureWebpack.js]: Ah, good point.  I may have turned off the rule that would yell at us for the superfluous global because I didn't want to change every source file in TerriaJS.  :)

In any case, no reason to add it to new source files!

Comment (kring) [inline buildprocess/configureWebpack.js]: Is the `'use strict'` superfluous as well?  I think it might be.

Comment (AlexGilleran) [inline buildprocess/configureWebpack.js]: Yeah afaik babel adds it

**Comment by AlexGilleran** [comment]
+1 from me

**Comment by stevage** [comment]
Just noting that this didn't build with Node 5.4.1:

```
[12:38:17] Error: Cannot find module 'entities/maps/entities.json'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.require.resolve (internal/module.js:23:19)
    at configureWebpack (/Users/stevebennett/odev/nicta/nationalmap/terriajs/buildprocess/configureWebpack.js:41:23)
    at Object.<anonymous> (/Users/stevebennett/odev/nicta/nationalmap/terriajs/buildprocess/webpack.config.js:27:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

Upgrading to 5.10 worked.

**Comment by kring** [comment]
I just merged in master, so now is a good time to merge this! ;)
